import type { Metadata } from "next";
import { RedirectToSignIn, Show } from "@clerk/nextjs";
import { Geist, Geist_Mono, Figtree, Noto_Serif } from "next/font/google";
import "@stream-io/video-react-sdk/dist/css/styles.css";
import "./globals.css";
import ConvexClerkProvider from "@/components/providers/ConvexClerkProvider";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

const notoSerif = Noto_Serif({ subsets: ["latin"], variable: "--font-serif" });

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html
        lang="en"
        suppressHydrationWarning
        className={cn(notoSerif.variable, "font-sans", figtree.variable)}
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Show when="signed-in">
              <div className=" min-h-screen">
                <Navbar />
                <main>{children}</main>
              </div>
            </Show>

            <Show when="signed-out">
              <RedirectToSignIn />
            </Show>
          </ThemeProvider>
          <Toaster />
        </body>
      </html>
    </ConvexClerkProvider>
  );
}
